# Generated by Django 4.2.23 on 2026-07-14 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Tuition, Library, Admission', max_length=100)),
                ('code', models.SlugField(blank=True, help_text='Unique short code (e.g., LIB, ADM, CREG)', null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[('gateway', 'Online (Gateway)'), ('manual', 'Bank Transfer/POS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('success', 'Verified/Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payments/proofs/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentcategory')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.semester')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
