# Generated by Django 4.2.23 on 2026-03-03 07:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('curriculum', '0003_alter_programme_name_alter_semester_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The total invoice amount due before this payment.', max_digits=10, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='The actual amount received in this payment transaction.', max_digits=10)),
                ('payment_date', models.DateField(blank=True, help_text='The date the payment was made by the student.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='The current status of the payment.', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('online_gateway', 'Online Gateway')], help_text='The method used for the payment.', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique ID from payment gateway or internal transaction ID.', max_length=100, null=True)),
                ('notes', models.CharField(blank=True, help_text='Any additional notes or remarks about the payment.', max_length=100, null=True)),
                ('is_installment', models.BooleanField(default=False, help_text='Check if this payment is part of an installment plan.')),
                ('installment_number', models.PositiveIntegerField(blank=True, help_text='The current installment number.', null=True)),
                ('total_installments', models.PositiveIntegerField(blank=True, help_text='The total number of installments.', null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount applied to the payment.', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount applied to the payment.', max_digits=5)),
                ('balance_before_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Balance remaining before this payment.', max_digits=10, null=True)),
                ('balance_after_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Balance remaining after this payment.', max_digits=10, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True, help_text='The date and time the payment was recorded.')),
                ('confirm_payment', models.BooleanField(default=False, verbose_name='confirm the payment')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the payment category (e.g., 'Tuition Fee JSS1', 'Hostel Fee JSS2').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the payment category.', null=True)),
            ],
            options={
                'verbose_name': 'Payment Category',
                'verbose_name_plural': 'Payment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcategory')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fee Assignment',
                'verbose_name_plural': 'Student Fee Assignments',
                'unique_together': {('student', 'payment_category', 'semester', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='A unique identifier for the receipt.', max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the receipt was issued.')),
                ('generated_by', models.ForeignKey(blank=True, help_text='The staff member who generated this receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(help_text='The payment associated with this receipt.', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH_DEPOSIT', 'Cash Deposit (Bank)'), ('POS', 'POS Transaction'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other Offline Method')], default='BANK_TRANSFER', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank/Gateway Transaction Reference (if any).', max_length=100, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PROCESSED', 'Processed (Payment Recorded)'), ('REJECTED', 'Rejected (Invalid Proof)')], default='PENDING', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes from the payer.')),
                ('bank_account', models.ForeignKey(blank=True, help_text='The specific school bank account the payment was made to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bankdetail', verbose_name='School Bank Account')),
                ('notified_by', models.ForeignKey(blank=True, help_text='User who submitted the form.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.semester')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student Paid For')),
            ],
            options={
                'verbose_name': 'Payment Notification',
                'verbose_name_plural': 'Payment Notifications',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.ForeignKey(help_text='The category of this payment (e.g., Tuition, Hostel).', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentcategory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The staff member who recorded this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.ForeignKey(help_text='The academic semester this payment is for.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='curriculum.semester'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(help_text='The academic session this payment is for.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(help_text='The student associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee_assignment',
            field=models.ForeignKey(blank=True, help_text='The specific fee assignment this payment applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.studentfeeassignment'),
        ),
        migrations.CreateModel(
            name='CategoryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(blank=True, help_text="A specific name for this fee instance (e.g., 'First Semester Tuition').", max_length=255, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='The level amount due for this category, semester, and session.', max_digits=10)),
                ('payment_category', models.ForeignKey(help_text='The payment category this fee applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='payments.paymentcategory')),
                ('semester', models.ForeignKey(help_text='The academic semester this fee applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='category_fees', to='curriculum.semester')),
                ('session', models.ForeignKey(help_text='The academic session this fee applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='category_fees', to='curriculum.session')),
                ('student_class', models.ForeignKey(blank=True, help_text='The class level this fee applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='curriculum.level')),
            ],
            options={
                'verbose_name': 'Category Fee',
                'verbose_name_plural': 'Category Fees',
                'ordering': ['session__name', 'semester__name', 'payment_category__name', 'fee_name'],
                'unique_together': {('payment_category', 'semester', 'session', 'student_class', 'fee_name')},
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='The actual amount this specific student owes.', max_digits=10)),
                ('category_fee', models.ForeignKey(help_text="The level fee category this student's fee is based on.", on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='payments.categoryfee')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='curriculum.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
                'unique_together': {('student', 'category_fee', 'semester', 'session')},
            },
        ),
        migrations.CreateModel(
            name='StudentAccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='The current balance for the student in this semester/session. Positive for debit, negative for credit.', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The last time this ledger entry was updated.')),
                ('semester', models.ForeignKey(help_text='The academic semester for this balance.', on_delete=django.db.models.deletion.PROTECT, related_name='student_ledgers', to='curriculum.semester')),
                ('session', models.ForeignKey(help_text='The academic session for this balance.', on_delete=django.db.models.deletion.PROTECT, related_name='student_ledgers', to='curriculum.session')),
                ('student', models.ForeignKey(help_text='The student whose account balance is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='account_ledgers', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Account Ledger',
                'verbose_name_plural': 'Student Account Ledgers',
                'ordering': ['student__user__last_name', 'session__name', 'semester__name'],
                'unique_together': {('student', 'semester', 'session')},
            },
        ),
        migrations.CreateModel(
            name='ClassFeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcategory')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_templates', to='curriculum.level')),
            ],
            options={
                'verbose_name': 'Class Fee Template',
                'verbose_name_plural': 'Class Fee Templates',
                'unique_together': {('student_class', 'semester', 'session', 'payment_category')},
            },
        ),
    ]
