# employees/core/choices.py

from django.db import models


class NigerianState(models.TextChoices):
    SELECT = "Select", "Select"
    ABIA = "Abia", "Abia"
    ADAMAWA = "Adamawa", "Adamawa"
    AKWA_IBOM = "Akwa Ibom", "Akwa Ibom"
    ANAMBRA = "Anambra", "Anambra"
    BAUCHI = "Bauchi", "Bauchi"
    BAYELSA = "Bayelsa", "Bayelsa"
    BENUE = "Benue", "Benue"
    BORNO = "Borno", "Borno"
    CROSS_RIVER = "Cross River", "Cross River"
    DELTA = "Delta", "Delta"
    EBONYI = "Ebonyi", "Ebonyi"
    EDO = "Edo", "Edo"
    EKITI = "Ekiti", "Ekiti"
    ENUGU = "Enugu", "Enugu"
    FCT_ABUJA = "FCT Abuja", "FCT Abuja"
    GOMBE = "Gombe", "Gombe"
    IMO = "Imo", "Imo"
    JIGAWA = "Jigawa", "Jigawa"
    KADUNA = "Kaduna", "Kaduna"
    KANO = "Kano", "Kano"
    KATSINA = "Katsina", "Katsina"
    KEBBI = "Kebbi", "Kebbi"
    KOGI = "Kogi", "Kogi"
    KWARA = "Kwara", "Kwara"
    LAGOS = "Lagos", "Lagos"
    NASARAWA = "Nasarawa", "Nasarawa"
    NIGER = "Niger", "Niger"
    OGUN = "Ogun", "Ogun"
    ONDO = "Ondo", "Ondo"
    OSUN = "Osun", "Osun"
    OYO = "Oyo", "Oyo"
    PLATEAU = "Plateau", "Plateau"
    RIVERS = "Rivers", "Rivers"
    SOKOTO = "Sokoto", "Sokoto"
    TARABA = "Taraba", "Taraba"
    YOBE = "Yobe", "Yobe"
    ZAMFARA = "Zamfara", "Zamfara"