# Generated by Django 4.2.23 on 2026-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_state_of_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'Administrative Departments', 'verbose_name_plural': 'Administrative Departments'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='activate',
            field=models.BooleanField(blank=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('select', 'select'), ('student', 'student'), ('lecturer', 'lecturer'), ('admin', 'admin'), ('other_staff', 'other_staff')], default='student', max_length=20, null=True),
        ),
    ]
