# Generated by Django 4.2.23 on 2026-03-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('matric_number', models.CharField(help_text='Must match username', max_length=100, unique=True)),
                ('date_admitted', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'B-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select', 'select')], max_length=15, null=True)),
                ('genotype', models.CharField(blank=True, max_length=5, null=True)),
                ('health_remark', models.CharField(blank=True, max_length=200)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_address', models.CharField(blank=True, max_length=200)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, choices=[('parent', 'Parent'), ('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('student_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('fee_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='curriculum.departments')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.programme')),
                ('user', models.OneToOneField(help_text='Select user or create new user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GraduationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_graduated', models.DateField()),
                ('remarks', models.CharField(blank=True, help_text='Optional remarks (Distinction, Upper Credit, etc.)', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.departments')),
                ('level_completed', models.ForeignKey(help_text='Final level completed (e.g. OND 2, HND 2)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.programme')),
                ('session', models.ForeignKey(blank=True, help_text='Session student completed programme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to='students.students')),
            ],
            options={
                'verbose_name': 'Graduation Record',
                'verbose_name_plural': 'Graduation Records',
                'ordering': ['-date_graduated'],
            },
        ),
    ]
