# Generated by Django 4.2.23 on 2026-04-15 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TEMPORARY_NAME', max_length=100, unique=True)),
                ('gender_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Total bed spaces in this hostel')),
                ('description', models.TextField(blank=True, help_text='Location details or rules')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('hostel_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to='staff.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('max_occupancy', models.PositiveIntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='students.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(help_text='Must match username', max_length=100, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_admitted', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('student_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('SW', 'Sandwich'), ('WK', 'Weekend')], default='FT', help_text='Select student enrollment category', max_length=2)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'B-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select', 'select')], max_length=15, null=True)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('select', 'select')], max_length=15, null=True)),
                ('health_remark', models.CharField(blank=True, max_length=200)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_address', models.CharField(blank=True, max_length=200)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, choices=[('parent', 'Parent'), ('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('student_status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('fee_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='students.room')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='curriculum.department')),
                ('hostel_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_hostel_name', to='students.hostel')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.programme')),
                ('user', models.OneToOneField(help_text='Select user or create new user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=60, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(help_text='The user account for this parent.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_graduated', models.DateField()),
                ('remarks', models.CharField(blank=True, help_text='Optional remarks (Distinction, Upper Credit, etc.)', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.department')),
                ('level_completed', models.ForeignKey(help_text='Final level completed (e.g. OND 2, HND 2)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.level')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.programme')),
                ('session', models.ForeignKey(blank=True, help_text='Session student completed programme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Graduation Record',
                'verbose_name_plural': 'Graduation Records',
                'ordering': ['-date_graduated'],
            },
        ),
    ]
