# Generated by Django 4.2.23 on 2026-03-01 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_departments_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraduationRecords',
            new_name='GraduationRecord',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
