# Generated by Django 4.2.23 on 2026-03-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_office_address_lecturer_address_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('day_student', 'day_student'), ('boarder', 'boarder')], default='day_student', max_length=15),
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hostel_master', models.ForeignKey(blank=True, help_text='select hostel master', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.lecturer')),
            ],
        ),
    ]
