# Generated by Django 4.2.23 on 2026-07-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
