# Generated by Django 4.2.23 on 2026-04-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_type_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hostel_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_name', to='students.hostel', verbose_name='hostel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('SW', 'Sandwich'), ('WK', 'Weekend')], default='FT', help_text='Select student enrollment category', max_length=2),
        ),
    ]
