# Generated by Django 4.2.23 on 2026-04-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_hostel_name_alter_student_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel_name',
            field=models.ForeignKey(blank=True, help_text='If allocated Hoste, Select Hostel Name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_name', to='students.hostel', verbose_name='hostel'),
        ),
    ]
