# Generated by Django 4.2.23 on 2026-04-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_hostel_desc_hostel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('select', 'select')], max_length=15, null=True),
        ),
    ]
