# Generated by Django 4.2.23 on 2026-04-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_genotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
