# Generated by Django 4.2.23 on 2026-07-14 22:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_mandatory_for_exam', models.BooleanField(default=True, help_text='If checked, a student cannot sit exams for ANY course this semester until this fee is cleared.')),
                ('allow_part_payment', models.BooleanField(default=True, help_text='Whether students may pay this fee in installments over time.')),
                ('clearance_threshold_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of `amount` that must be paid for this fee to count as cleared. Usually 100.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Fee Assignment',
                'verbose_name_plural': 'Fee Assignments',
                'ordering': ['session', 'semester', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Transaction reference / receipt number.', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('ussd', 'USSD'), ('wallet', 'Wallet'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Bursary staff who recorded a manual/offline payment; blank for an online gateway payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('record_payment', 'Can record student payments'), ('view_finance_reports', 'Can view finance collection reports')],
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_item', to='curriculum.courseregistration')),
                ('fee_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='finance.feeassignment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='curriculum.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='students.student')),
            ],
            options={
                'verbose_name': 'Payment Item',
                'verbose_name_plural': 'Payment Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment')),
                ('payment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.paymentitem')),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
            },
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='finance.feecategory'),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='curriculum.level'),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='curriculum.programme'),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='curriculum.semester'),
        ),
        migrations.AddField(
            model_name='feeassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='curriculum.session'),
        ),
        migrations.AddIndex(
            model_name='paymentitem',
            index=models.Index(fields=['student', 'session', 'semester'], name='finance_pay_student_3aba97_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('course_registration__isnull', False), ('fee_assignment__isnull', True)), models.Q(('course_registration__isnull', True), ('fee_assignment__isnull', False)), _connector='OR'), name='payment_item_exactly_one_target'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentitem',
            unique_together={('student', 'fee_assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'payment_item')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'status'], name='finance_pay_student_237141_idx'),
        ),
        migrations.AddIndex(
            model_name='feeassignment',
            index=models.Index(fields=['session', 'semester', 'programme', 'level'], name='finance_fee_session_ff5bfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeassignment',
            unique_together={('category', 'programme', 'level', 'session', 'semester')},
        ),
    ]
