# Generated by Django 4.2.23 on 2026-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
    ]
