# Generated by Django 4.2.23 on 2026-07-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_schoolbankdetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolbankdetail',
            unique_together={('acc_number', 'bank_name')},
        ),
    ]
