# Generated by Django 4.2.23 on 2026-03-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Do not enter anything here', null=True)),
            ],
            options={
                'verbose_name': 'Staff Roles',
                'verbose_name_plural': 'Staff Roles',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('date_employed', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('office_address', models.CharField(blank=True, max_length=200)),
                ('highest_qualification', models.CharField(max_length=150)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='curriculum.departments')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffposition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'ordering': ['user__last_name'],
            },
        ),
    ]
