# Generated by Django 4.2.23 on 2026-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='office_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
