# Generated by Django 4.2.23 on 2026-04-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_comment_elearningsubject_reply_lesson_and_more'),
        ('staff', '0002_rename_office_address_lecturer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='curriculum.department'),
        ),
    ]
