# Generated by Django 4.2.23 on 2026-04-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_lecturer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='staff_id',
        ),
    ]
