# Generated by Django 4.2.23 on 2026-07-17 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elearning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0004_alter_courseregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document / Slides'), ('note', 'Written Note'), ('link', 'External Link / Resource')], default='note', max_length=20)),
                ('week_number', models.PositiveSmallIntegerField(default=1, help_text='Used to order material within the course, e.g. Week 1, Week 2.', verbose_name='Week / Position')),
                ('description', models.TextField(blank=True, help_text='Plain text notes/summary. Keep formatting simple — no rich text editor required.')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube, Google Drive, or Vimeo link.', verbose_name='Video link')),
                ('file', models.FileField(blank=True, null=True, upload_to=elearning.models.material_upload_path, verbose_name='Attachment (PDF, slides, doc, etc.)')),
                ('external_link', models.URLField(blank=True, help_text='Any other external resource link.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to save as a draft, hidden from students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_materials', to='curriculum.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_course_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
                'ordering': ['course', 'week_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='elearning.coursematerial')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineClassLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_classroom', 'Google Classroom'), ('ms_teams', 'Microsoft Teams')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional display name, e.g. 'Weekly Lecture' or 'Lab Session'.", max_length=150)),
                ('join_link', models.URLField(help_text='Paste the Google Classroom invite link (classroom.google.com/c/...) or the Microsoft Teams class/meeting link here.')),
                ('class_code', models.CharField(blank=True, help_text='Optional. Google Classroom class code, shown for students who join manually.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_class_links', to='curriculum.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Class Link',
                'verbose_name_plural': 'Online Class Links',
                'ordering': ['course', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='elearning.materialcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
