# Generated by Django 4.2.23 on 2026-07-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'CBT Setting', 'verbose_name_plural': 'CBT Settings'},
        ),
    ]
