# Generated by Django 4.2.23 on 2026-03-02 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('results', '0001_initial'),
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='results.examination'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='curriculum.programme'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_session', to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.question'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('examination', 'course', 'semester', 'session'), name='unique_quiz_per_exam_context'),
        ),
    ]
