# Generated by Django 4.2.23 on 2026-03-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_programme_name_alter_semester_name'),
        ('cbt', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='programme',
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='curriculum.level'),
            preserve_default=False,
        ),
    ]
