# Generated by Django 4.2.23 on 2026-03-02 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heading_department', to='staff.lecturer'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='staff.lecturer'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.semester'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='staff.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programme'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('lecturer', 'course', 'session', 'semester')},
        ),
    ]
