# Generated by Django 4.2.23 on 2026-03-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('staff', '0001_initial'),
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
