# Generated by Django 4.2.23 on 2026-05-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolidentity',
            options={},
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='address_line_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='identity_label',
            field=models.CharField(help_text='e.g. Main, Faculty of Science, School of Engineering', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='logo',
            field=models.ImageField(default='school_logo.jpg', upload_to='official_pics'),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='phone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='official_pics'),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AcademicIdentityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.faculty')),
                ('school_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.schoolidentity')),
            ],
        ),
    ]
