# Generated by Django 4.2.23 on 2026-03-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(choices=[('OND', 'OND'), ('HND', 'HND'), ('CERTIFICATE', 'CERTIFICATE'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester'), ('Third', 'Third Semester')], max_length=20),
        ),
    ]
