# Generated by Django 4.2.23 on 2026-07-15 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0003_course_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'permissions': [('validate_registration', 'Can validate course registrations')]},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Registrar has confirmed this registration is correct. Required (alongside fee clearance) for exam eligibility.'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
