# Generated by Django 4.2.23 on 2026-04-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_comment_elearningsubject_reply_lesson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolidentity',
            options={'verbose_name': 'School Identity Setting', 'verbose_name_plural': 'School Identity Settings'},
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='identity_label',
            field=models.CharField(blank=True, help_text='e.g. Primary, Secondary, or Main', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Fallback identity if no specific class identity is set.'),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
