# Generated by Django 4.2.23 on 2026-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_courseregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('compulsory', 'Compulsory'), ('elective', 'Elective')], default='compulsory', help_text="Compulsory courses count toward the required-to-graduate total; electives are shown separately and don't block graduation progress.", max_length=12),
        ),
    ]
