# Generated by Django 4.2.23 on 2026-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_course_course_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elearningsubject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='elearningsubject',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment_name',
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='hr_email',
            field=models.EmailField(blank=True, help_text='HR / Staff Affairs email — shown to lecturers & staff', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='hr_phone',
            field=models.CharField(blank=True, help_text='HR / Staff Affairs phone — shown to lecturers & staff', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='registrar_email',
            field=models.EmailField(blank=True, help_text='Registry / Student Affairs email — shown to students', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='registrar_phone',
            field=models.CharField(blank=True, help_text='Registry / Student Affairs phone — shown to students', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Portal/ICT support email — for technical issues, shown to students & staff', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='support_phone',
            field=models.CharField(blank=True, help_text='Portal/ICT support phone — for technical issues, shown to students & staff', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ELearningSubject',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
