# Generated by Django 4.2.23 on 2026-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_department_faculty_alter_department_hod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicidentitymapping',
            options={'verbose_name': 'School Identity Mapping (Branch)', 'verbose_name_plural': 'School Identity Mapping (Branch)'},
        ),
        migrations.AlterModelOptions(
            name='schoolidentity',
            options={'verbose_name': 'School Main Identity', 'verbose_name_plural': 'School Main Identity'},
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='authorized_signature',
            field=models.ImageField(blank=True, help_text="Transparent-background PNG of this signatory's signature works best.", null=True, upload_to='signatures/authorized/'),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='authorized_signee_name',
            field=models.CharField(blank=True, help_text='Full name of the second authorized signatory (e.g. the Vice Chancellor/Rector).', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='authorized_signee_title',
            field=models.CharField(blank=True, default='Vice Chancellor', help_text="Official title, e.g. 'Vice Chancellor', 'Rector', 'Provost', 'Director'.", max_length=100),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='registrar_name',
            field=models.CharField(blank=True, help_text='Full name of the Registrar, as it should appear on official documents.', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='registrar_signature',
            field=models.ImageField(blank=True, help_text="Transparent-background PNG of the Registrar's signature works best.", null=True, upload_to='signatures/registrar/'),
        ),
    ]
