# Generated by Django 4.2.23 on 2026-07-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='audience',
            field=models.CharField(blank=True, choices=[('all', 'All Users'), ('lecturers', 'Lecturers'), ('students', 'Students')], default='all', help_text='Who a broadcast ticket/announcement is addressed to. Ignored for regular tickets.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Course Registration', 'Course Registration'), ('Examinations & Results', 'Examinations & Results'), ('Academic', 'Academic (Other)'), ('Financial Aid', 'Financial Aid / Bursary'), ('Hostel/Accommodation', 'Hostel / Accommodation'), ('ID Card', 'ID Card'), ('Technical Support', 'Technical Support (Portal/ICT)'), ('Facilities', 'Facilities'), ('General Inquiry', 'General Inquiry')], default='General Inquiry', max_length=50),
        ),
    ]
