# Generated by Django 4.2.23 on 2026-04-15 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='A', max_length=1)),
                ('remarks', models.CharField(blank=True, help_text="e.g., 'Student left early for clinic'", max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date', 'course', 'student__middle_name'],
            },
        ),
    ]
