# Generated by Django 4.2.23 on 2026-07-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('curriculum', '0008_alter_academicidentitymapping_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exam Venue',
                'verbose_name_plural': 'Exam Venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructions', models.TextField(blank=True, help_text="Special instructions shown on the student timetable, e.g. 'Bring your calculator.'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='curriculum.course')),
                ('invigilators', models.ManyToManyField(blank=True, related_name='invigilation_duties', to='staff.lecturer')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='curriculum.semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='curriculum.session')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='examinations.examvenue')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'ordering': ['exam_date', 'start_time'],
                'indexes': [models.Index(fields=['session', 'semester', 'exam_date'], name='examination_session_3d2037_idx')],
                'unique_together': {('course', 'session', 'semester')},
            },
        ),
    ]
